name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend → statvora.in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy statvora-frontend
        working-directory: tether-frontend
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_w61EPm8QPeCRNJAt1TAYUX2a
          VERCEL_PROJECT_ID: prj_7bF4HTZL1AATeT9CXOpAcXdpDX9I

  deploy-backend:
    name: Deploy Backend → api.statvora.in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy statvora-backend
        working-directory: tether-backend
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_w61EPm8QPeCRNJAt1TAYUX2a
          VERCEL_PROJECT_ID: prj_DwCyPlnCTFDbE3vGTnowRTboTynv
